use mr::worker::KeyValue;

/// The map function is called once for each file input. The first
/// argument is the name of the input file, and the second is the
/// file's complete contents. You should ignore the input file name,
/// and look only at the contents argument. The return value is a slice
/// of key/value pairs.
pub fn map(_key: &str, value: &str) -> Vec<KeyValue> {
    let mut res = Vec::new();
    for word in value
        .split(|c: char| !c.is_alphabetic())
        .filter(|s| !s.is_empty())
    {
        res.push(KeyValue {
            key: word.to_string(),
            value: "1".to_owned(),
        });
    }
    res
}

/// The reduce function is called once for each key generated by the
/// map tasks, with a list of all the values created for that key by
/// any map task
pub fn reduce(_key: &str, values: &[String]) -> String {
    values.len().to_string()
}
